import type { Metadata } from "next";
import "./globals.css";
import SessionAuthProvider from "@/context/SesionProvider";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <SessionAuthProvider>
            {children}
          </SessionAuthProvider>
        </div>
      </body>
    </html>
  );
}
